import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
       

      <body className="min-h-full flex flex-col">
         {/* Logged Out */}
            <Navbar  />
      
            {/* OR — Logged In */}
            {/* <Navbar
              scrolled={scrolled}
              isLoggedIn={true}
              user={{
                name: "Rahul Sharma",
                email: "rahul@example.com",
                avatar: "/avatar.jpg",
                isHost: true,
              }}
              onSignIn={() => console.log("Sign in")}
              onSignUp={() => console.log("Sign up")}
              onLogout={() => console.log("Logout")}
            />  */}
        {children}
        </body>
    </html>
  );
}
