import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import HappyStayFooter from "@/components/footer";
import LayoutWrapper from "@/components/layoutwrapper/layoutwrapper";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
       

      <body className="min-h-full flex flex-col">
        <LayoutWrapper>
          {children}
          </LayoutWrapper>
        
       
      
        </body>
    </html>
  );
}
